### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by ju-to-sh** [ju-to-sh/TypingPlus#41]
### 概要
タイピングとRuby/Railsの学習が１つのサイトでできるRuby/Rails特化の学習アプリ作成を行います。開発に必要な機能とページについては以下のとおりです。

### 実装予定の機能
**【MVPリリース時】**<br>
- [ ] ログイン機能
- [ ] ゲストログイン機能
- [ ] 検索機能
- [ ] プロフィール画像投稿機能
- [ ] タイピング練習機能
- [ ] クイズ機能
- [ ] 学習記録管理機能
- [ ] ユーザーのCRUD機能
- [ ] Xへの投稿機能
- [ ] ランキング表示機能
- [ ] お気に入り機能

**【本リリース時】**<br>
- [ ] タイピング実績のグラフ化
- [ ] 学習日実績の見える化（Githubの草のようなイメージ）
- [ ] 管理者画面
- [ ] CSVインポート・エクスポート機能

### 必要なページ
- [ ] トップページ
- [ ] ログインページ
- [ ] 会員登録ページ
- [ ] マイページ
- [ ] 利用規約ページ
- [ ] プライバシーポリシーページ
- [ ] ゲーム選択ページ
- [ ] クイズ一覧ページ
- [ ] クイズ問題ページ
- [ ] クイズ結果ページ
- [ ] タイピング一覧ページ
- [ ] タイピング問題ページ
- [ ] タイピング結果ページ
- [ ] 検索結果ページ
- [ ] ランキング一覧ページ
- [ ] お気に入り一覧ページ
- [ ] 学習記録ページ
- [ ] 管理者画面

**Comment by Tsuchiya2** [comment]
![image](https://github.com/ju-to-sh/TypingPlus/assets/61481161/debe5c26-db3e-4f99-ab9a-bc73704c6c76)

projectsにアクセスしましたが、看板・issue・ストーリーポイントが確認できまんでした。
上記確認できる状態で再提出をお願いいたします。

**Comment by ju-to-sh** [comment]
Projectsの公開がprivateのままになっており申し訳ありませんでした。
publicに変更したため確認いただけるかと思いますので、レビューのほど宜しくお願いいたします。

**Comment by Tsuchiya2** [comment]
<img width="591" alt="image" src="https://github.com/ju-to-sh/TypingPlus/assets/61481161/fe5f6f0a-43fa-4fa4-b8c2-b56291c4bd50">

先程、確認してみましたが、projectsには何も表示されず...
再度ご確認をお願いいたします。

**Comment by ju-to-sh** [comment]
申し訳ありません。
以下のリンクよりご確認頂けますでしょうか？
https://github.com/users/ju-to-sh/projects/1

**Comment by ju-to-sh** [comment]
Projectsが表示されなかったのは、projectの作成場所がアプリ開発用のレポジトリ内ではなく、ユーザー画面のProjectsから作成していたためでした。
Projectをリンクさせる方法がありましたので、一旦そちらで対応しております。
ご迷惑をおかけして申し訳ありませんが、引き続きよろしくお願いいたします。

**Comment by tarakish** [comment]
確認できました。LGTMです！
MVPリリースに向けて開発頑張ってください。

**Comment by ju-to-sh** [comment]
ご確認頂きありがとうございました。
