### ISSUE TITLE
MVPリリース時のレビュー依頼

### ISSUE THREAD

**Issue by ju-to-sh** [ju-to-sh/TypingPlus#53]
MVPリリース前のレビュー依頼になります。お忙しいところ大変恐縮ですが、レビューの程よろしくお願いいたします。

## 各種情報
サービス名：Typing Plus
サービス概要：Ruby/Railsに特化したクイズとタイピングゲームができるサービスです。
サービスURL：https://typing-plus-front.vercel.app/
フロントエンドとバックエンドを分けて開発しています。各アプリのリポジトリは以下の通りです。
フロントエンド：https://github.com/ju-to-sh/TypingPlus-front
バックエンド：https://github.com/ju-to-sh/typing_plus_api
## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [ ] ログイン機能
- [ ] ゲストログイン機能
- [ ] 検索機能
- [ ] プロフィール画像投稿機能
- [ ] タイピング練習機能
- [ ] クイズ機能
- [ ] 学習記録管理機能
- [ ] ユーザーのCRUD機能
- [ ] Xへの投稿機能
- [ ] ランキング表示機能
- [ ] お気に入り機能

実装済みの機能については、以下のURLより確認可能です。（〇〇は個別のIDが入ります）
ログイン機能：https://typing-plus-front.vercel.app/login
プロフィール画像投稿機能：https://typing-plus-front.vercel.app/users/〇〇（ログイン必須）
ユーザーのCRUD機能：https://typing-plus-front.vercel.app/signup
タイピング練習機能：https://typing-plus-front.vercel.app/typing_games/〇〇
クイズ機能：https://typing-plus-front.vercel.app/quizzes/〇〇

## READMEレビュー時から変更した機能
卒業認定までの開発スケジュール見積もり面談時に、MVPリリース時に必要な機能のみに絞り込んだため、以下の機能はMVPリリース後に変更した。
- [ ] ゲストログイン機能
- [ ] 検索機能
- [ ] 学習記録管理機能
- [ ] Xへの投稿機能
- [ ] ランキング表示機能
- [ ] お気に入り機能

## サービスイメージがわかるようなスクリーンショット等
[クイズゲーム画面](https://gyazo.com/4715979b1c8a02719fed254a77de102d)
[タイピングゲーム画面](https://gyazo.com/0bb12ee7feef886b2e818c39c1fbd139)

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。

**Comment by ju-to-sh** [comment]
ご確認いただきありがとうございました。引き続きよろしくお願いいたします。
