### ISSUE TITLE
X認証におけるエラーに関する質問

### ISSUE THREAD

**Issue by ju-to-sh** [ju-to-sh/TypingPlus#59]
X投稿機能を実装中に解決できないエラーが発生しました。内容をご確認頂き、アドバイス頂けると幸いです。

### 実装したい機能
タイピングゲーム結果をXに投稿できるようにしたい

### 解決したい内容
X認証のURLにリダイレクトされているようだが、OAuth::Unauthorized (401 Unauthorized):のエラーが発生するため、認証が通るようにしたい

### エラー時のログ
```
api-1    | Started GET "/api/v1/oauth/twitter" for 192.168.65.1 at 2024-08-01 23:17:26 +0900
api-1    | Processing by Api::V1::OauthsController#oauth as JSON
api-1    |   Parameters: {"provider"=>"twitter"}
api-1    | Redirected to https://api.twitter.com/oauth/authenticate?oauth_callback=http%3A%2F%2F127.0.0.1%3A3001%2Fapi%2Fv1%2Foauth%2Fcallback%3Fprovider%3Dtwitter&oauth_token=KMYOwgAAAAABvG_WAAABkQ5Ng_k
api-1    | Completed 302 Found in 414ms (ActiveRecord: 0.0ms | Allocations: 4575)
```
上記の内容が表示された後に、api/log/development.logの内容を確認し、リダイレクト先にアクセスすると、以下のログが出力されました。
```
api-1    | Started GET "/api/v1/oauth/callback?provider=twitter&oauth_token=[FILTERED]&oauth_verifier=IOch4Lzh1oSF3l1bmnEMQYsL9Gf8mC0m" for 192.168.65.1 at 2024-08-01 23:17:42 +0900
api-1    | Processing by Api::V1::OauthsController#callback as JSON
api-1    |   Parameters: {"provider"=>"twitter", "oauth_token"=>"[FILTERED]", "oauth_verifier"=>"IOch4Lzh1oSF3l1bmnEMQYsL9Gf8mC0m"}
api-1    | Completed 500 Internal Server Error in 998ms (ActiveRecord: 0.0ms | Allocations: 6365)
api-1    |
api-1    | OAuth::Unauthorized (401 Unauthorized):
api-1    |
api-1    | app/controllers/api/v1/oauths_controller.rb:12:in `callback'
```

### エラーの意味と推測される原因
Oauthの認証失敗。
推測される原因：認証に必要な情報が足りない

### 実装する際に参考にした資料
sorceryの公式wiki
https://github.com/Sorcery/sorcery/wiki/External
【Rails】SorceryでTwitter認証【2022年12月版
https://qiita.com/zakirun/items/da012e6d8f7282c3c912
### エラー解決するために調べた資料
Twitterログイン認証で404(forbidden)や401(Unauthorized)エラーがでたときの対処法
https://qiita.com/ngron/items/1f9d315e5ec0f4ae6098
OAuthの認証フロー
https://developer.x.com/en/docs/tutorials/authenticating-with-twitter-api-for-enterprise/oauth1-0a-and-user-access-tokens
### 確認した内容
・XのAPIキーとシークレットが正しいか確認し、入力間違いがないことを確認済み。
・リダイレクトURI：OAuthのリダイレクトURIがXの開発者コンソールで設定されているものと一致しているか確認済み。
・oauths_controller.rbのoauthメソッドとcallbackメソッドにbinding.pryを設置し、ログ出力を確認。oauthメソッドの処理は実行されていたが、callbackメソッドは先頭行に設置しても処理が止まらなかった。
https://gyazo.com/f8ca4cf3bf6a81fb0e77c9b83a55913a
### 現在の実装したコード（関連箇所のみ抜粋）
api/config/initializers/sorcery.rb
```ruby
Rails.application.config.sorcery.submodules = [:external]

Rails.application.config.sorcery.configure do |config|

  config.external_providers = [:twitter]

  config.twitter.key = ENV['TWITTER_API_KEY']
  config.twitter.secret = ENV['TWITTER_API_SECRET']
  config.twitter.callback_url = Settings.sorcery[:callback_url]
  config.twitter.user_info_mapping = {:email => "screen_name"}

  config.user_config do |user|

    user.stretches = 1 if Rails.env.test?
    user.authentications_class = Authentication

  end

  config.user_class = "User"
end
```
api/config/initializers/config.rb
```ruby
Config.setup do |config|
  config.const_name = 'Settings'
  config.env_prefix = 'SETTINGS'
end
```
api/config/settings/development.yml
```ruby
sorcery:
  callback_url: "http://127.0.0.1:3001/api/v1/oauth/callback?provider=twitter"
```
api/config/routes.rb
```ruby
Rails.application.routes.draw do
  namespace :api, format: 'json' do
    namespace :v1 do
      post 'oauth/callback' => 'oauths#callback'
      get 'oauth/callback' => 'oauths#callback'
      get 'oauth/:provider' => 'oauths#oauth'
    end
  end
end
```
api/app/controllers/api/v1/oauths_controller.rb
```ruby
module Api
  module V1
    class OauthsController < ApplicationController
      skip_before_action :authenticate, raise: false

      def oauth
        login_at(params[:provider])
      end

      def callback
        provider = params[:provider]
        if @user = login_from(provider)
          render json: { message: "Logged in from #{provider.titleize}!" }
        else
          begin
            @user = create_from(provider)
            reset_session
            auto_login(@user)
            render json: { message: "Logged in from #{provider.titleize}!" }
          rescue
            render json: { message: "Failed to login from #{provider.titleize}!" }
          end
        end
      end
    end
  end
end
```
api/app/models/authentication.rb
```ruby
class Authentication < ApplicationRecord
  belongs_to :user
end
```
api/app/models/user.rb
```ruby
class User < ApplicationRecord
  authenticates_with_sorcery!
  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications
end
```

**Comment by tmtkzk0823** [comment]
1点確認させてください！
Xへの投稿であれば、認証を通さなくてもクエリパラメータを用いてできたイメージなのですが、認証を通さないといけない理由はあったりしますでしょうか？

**Comment by ju-to-sh** [comment]
@tmtkzk0823 
Xに投稿するユーザーは、ゲームを実施した各ユーザーを想定しています。Xへのログイン後にゲーム結果が記載された状態ですぐに投稿できるようなイメージを考えていました。（具体例で言うと、寿司打をプレイした後のXに投稿ボタンを押した処理と同じ動作を再現したいです）
他のユーザーも同様に動作するには、認証が必須かと思っていましたが、アプリ自体にキー情報が付与されているので、アプリ使用者に変動があってもクエリパラメータで実装可能と言うことでしょうか？

**Comment by tmtkzk0823** [comment]
@ju-to-sh 
おやすみをもらっており、返信遅くなり申し訳ありません！
> 他のユーザーも同様に動作するには、認証が必須かと思っていましたが、アプリ自体にキー情報が付与されているので、アプリ使用者に変動があってもクエリパラメータで実装可能と言うことでしょうか？

上記の想定です！
[こちら](https://qiita.com/keitah/items/6bce3913c3f9f4415693)の記事が参考になるかと思います！
